//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SQLFinalEntities : DbContext
    {
        public SQLFinalEntities()
            : base("name=SQLFinalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<CD> CD { get; set; }
        public virtual DbSet<Cust> Cust { get; set; }
        public virtual DbSet<Interests> Interests { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    
        public virtual int Add_Cust(Nullable<int> param1, string param2, string param3, Nullable<int> param4, string param5, string param6)
        {
            var param1Parameter = param1.HasValue ?
                new ObjectParameter("param1", param1) :
                new ObjectParameter("param1", typeof(int));
    
            var param2Parameter = param2 != null ?
                new ObjectParameter("param2", param2) :
                new ObjectParameter("param2", typeof(string));
    
            var param3Parameter = param3 != null ?
                new ObjectParameter("param3", param3) :
                new ObjectParameter("param3", typeof(string));
    
            var param4Parameter = param4.HasValue ?
                new ObjectParameter("param4", param4) :
                new ObjectParameter("param4", typeof(int));
    
            var param5Parameter = param5 != null ?
                new ObjectParameter("param5", param5) :
                new ObjectParameter("param5", typeof(string));
    
            var param6Parameter = param6 != null ?
                new ObjectParameter("param6", param6) :
                new ObjectParameter("param6", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Add_Cust", param1Parameter, param2Parameter, param3Parameter, param4Parameter, param5Parameter, param6Parameter);
        }
    }
}
